'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30311.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class _Default
    
    Protected headContent As Global.System.Web.UI.WebControls.Content
    
    Protected Content1 As Global.System.Web.UI.WebControls.Content
    
    Protected ScriptManagerProxy1 As Global.System.Web.UI.ScriptManagerProxy
    
    Protected Menu1 As Global.System.Web.UI.WebControls.GridView
    
    Protected HyperLink1 As Global.System.Web.DynamicData.DynamicHyperLink
End Class
