
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("f9afc824-4441-4b43-9e42-a4ff95c72946")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("QLHSModel", "FK_checks_study_dates", "study_dates", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(study_dates), "checks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(check), True)>
<Assembly: EdmRelationshipAttribute("QLHSModel", "FK_checks_users", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(user), "checks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(check), True)>
<Assembly: EdmRelationshipAttribute("QLHSModel", "FK_classes_m_statuses", "m_statuses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(m_statuses), "classes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType([class]), True)>
<Assembly: EdmRelationshipAttribute("QLHSModel", "FK_classes_users", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(user), "classes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType([class]), True)>
<Assembly: EdmRelationshipAttribute("QLHSModel", "FK_scores_classes", "classes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType([class]), "scores", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(score), True)>
<Assembly: EdmRelationshipAttribute("QLHSModel", "FK_study_dates_classes", "classes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType([class]), "study_dates", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(study_dates), True)>
<Assembly: EdmRelationshipAttribute("QLHSModel", "FK_users_m_roles", "m_roles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(m_roles), "users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(user), True)>
<Assembly: EdmRelationshipAttribute("QLHSModel", "FK_scores_users", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(user), "scores", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(score), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class QLHSEntities1
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new QLHSEntities1 object using the connection string found in the 'QLHSEntities1' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=QLHSEntities1", "QLHSEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new QLHSEntities1 object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "QLHSEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new QLHSEntities1 object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "QLHSEntities1")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property checks() As ObjectSet(Of check)
        Get
            If (_checks Is Nothing) Then
                _checks = MyBase.CreateObjectSet(Of check)("checks")
            End If
            Return _checks
        End Get
    End Property

    Private _checks As ObjectSet(Of check)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property classes() As ObjectSet(Of [class])
        Get
            If (_classes Is Nothing) Then
                _classes = MyBase.CreateObjectSet(Of [class])("classes")
            End If
            Return _classes
        End Get
    End Property

    Private _classes As ObjectSet(Of [class])

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property m_roles() As ObjectSet(Of m_roles)
        Get
            If (_m_roles Is Nothing) Then
                _m_roles = MyBase.CreateObjectSet(Of m_roles)("m_roles")
            End If
            Return _m_roles
        End Get
    End Property

    Private _m_roles As ObjectSet(Of m_roles)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property m_statuses() As ObjectSet(Of m_statuses)
        Get
            If (_m_statuses Is Nothing) Then
                _m_statuses = MyBase.CreateObjectSet(Of m_statuses)("m_statuses")
            End If
            Return _m_statuses
        End Get
    End Property

    Private _m_statuses As ObjectSet(Of m_statuses)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property scores() As ObjectSet(Of score)
        Get
            If (_scores Is Nothing) Then
                _scores = MyBase.CreateObjectSet(Of score)("scores")
            End If
            Return _scores
        End Get
    End Property

    Private _scores As ObjectSet(Of score)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property study_dates() As ObjectSet(Of study_dates)
        Get
            If (_study_dates Is Nothing) Then
                _study_dates = MyBase.CreateObjectSet(Of study_dates)("study_dates")
            End If
            Return _study_dates
        End Get
    End Property

    Private _study_dates As ObjectSet(Of study_dates)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property users() As ObjectSet(Of user)
        Get
            If (_users Is Nothing) Then
                _users = MyBase.CreateObjectSet(Of user)("users")
            End If
            Return _users
        End Get
    End Property

    Private _users As ObjectSet(Of user)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the checks EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTochecks(ByVal check As check)
        MyBase.AddObject("checks", check)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the classes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToclasses(ByVal [class] As [class])
        MyBase.AddObject("classes", [class])
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the m_roles EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTom_roles(ByVal m_roles As m_roles)
        MyBase.AddObject("m_roles", m_roles)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the m_statuses EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTom_statuses(ByVal m_statuses As m_statuses)
        MyBase.AddObject("m_statuses", m_statuses)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the scores EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToscores(ByVal score As score)
        MyBase.AddObject("scores", score)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the study_dates EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTostudy_dates(ByVal study_dates As study_dates)
        MyBase.AddObject("study_dates", study_dates)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTousers(ByVal user As user)
        MyBase.AddObject("users", user)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLHSModel", Name:="check")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class check
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new check object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="student_id">Initial value of the student_id property.</param>
    ''' <param name="date_id">Initial value of the date_id property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createcheck(id As Global.System.Int32, student_id As Global.System.Int32, date_id As Global.System.Int32, delflg As Global.System.Int32) As check
        Dim check as check = New check
        check.id = id
        check.student_id = student_id
        check.date_id = date_id
        check.delflg = delflg
        Return check
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property student_id() As Global.System.Int32
        Get
            Return _student_id
        End Get
        Set
            Onstudent_idChanging(value)
            ReportPropertyChanging("student_id")
            _student_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("student_id")
            Onstudent_idChanged()
        End Set
    End Property

    Private _student_id As Global.System.Int32
    Private Partial Sub Onstudent_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onstudent_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property date_id() As Global.System.Int32
        Get
            Return _date_id
        End Get
        Set
            Ondate_idChanging(value)
            ReportPropertyChanging("date_id")
            _date_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("date_id")
            Ondate_idChanged()
        End Set
    End Property

    Private _date_id As Global.System.Int32
    Private Partial Sub Ondate_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondate_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_checks_study_dates", "study_dates")>
    Public Property study_dates() As study_dates
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of study_dates)("QLHSModel.FK_checks_study_dates", "study_dates").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of study_dates)("QLHSModel.FK_checks_study_dates", "study_dates").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property study_datesReference() As EntityReference(Of study_dates)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of study_dates)("QLHSModel.FK_checks_study_dates", "study_dates")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of study_dates)("QLHSModel.FK_checks_study_dates", "study_dates", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_checks_users", "users")>
    Public Property user() As user
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_checks_users", "users").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_checks_users", "users").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property userReference() As EntityReference(Of user)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_checks_users", "users")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of user)("QLHSModel.FK_checks_users", "users", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLHSModel", Name:="class")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class [class]
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new class object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="class_name">Initial value of the class_name property.</param>
    ''' <param name="hour">Initial value of the hour property.</param>
    ''' <param name="teacher_id">Initial value of the teacher_id property.</param>
    ''' <param name="status_id">Initial value of the status_id property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createclass(id As Global.System.Int32, class_name As Global.System.String, hour As Global.System.String, teacher_id As Global.System.Int32, status_id As Global.System.Int32, delflg As Global.System.Int32) As [class]
        Dim [class] as [class] = New [class]
        [class].id = id
        [class].class_name = class_name
        [class].hour = hour
        [class].teacher_id = teacher_id
        [class].status_id = status_id
        [class].delflg = delflg
        Return [class]
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property class_name() As Global.System.String
        Get
            Return _class_name
        End Get
        Set
            Onclass_nameChanging(value)
            ReportPropertyChanging("class_name")
            _class_name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("class_name")
            Onclass_nameChanged()
        End Set
    End Property

    Private _class_name As Global.System.String
    Private Partial Sub Onclass_nameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onclass_nameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property hour() As Global.System.String
        Get
            Return _hour
        End Get
        Set
            OnhourChanging(value)
            ReportPropertyChanging("hour")
            _hour = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("hour")
            OnhourChanged()
        End Set
    End Property

    Private _hour As Global.System.String
    Private Partial Sub OnhourChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnhourChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property teacher_id() As Global.System.Int32
        Get
            Return _teacher_id
        End Get
        Set
            Onteacher_idChanging(value)
            ReportPropertyChanging("teacher_id")
            _teacher_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("teacher_id")
            Onteacher_idChanged()
        End Set
    End Property

    Private _teacher_id As Global.System.Int32
    Private Partial Sub Onteacher_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onteacher_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property description() As Global.System.String
        Get
            Return _description
        End Get
        Set
            OndescriptionChanging(value)
            ReportPropertyChanging("description")
            _description = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("description")
            OndescriptionChanged()
        End Set
    End Property

    Private _description As Global.System.String
    Private Partial Sub OndescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property date_begin() As Nullable(Of Global.System.DateTime)
        Get
            Return _date_begin
        End Get
        Set
            Ondate_beginChanging(value)
            ReportPropertyChanging("date_begin")
            _date_begin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("date_begin")
            Ondate_beginChanged()
        End Set
    End Property

    Private _date_begin As Nullable(Of Global.System.DateTime)
    Private Partial Sub Ondate_beginChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Ondate_beginChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property date_end() As Nullable(Of Global.System.DateTime)
        Get
            Return _date_end
        End Get
        Set
            Ondate_endChanging(value)
            ReportPropertyChanging("date_end")
            _date_end = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("date_end")
            Ondate_endChanged()
        End Set
    End Property

    Private _date_end As Nullable(Of Global.System.DateTime)
    Private Partial Sub Ondate_endChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub Ondate_endChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property status_id() As Global.System.Int32
        Get
            Return _status_id
        End Get
        Set
            Onstatus_idChanging(value)
            ReportPropertyChanging("status_id")
            _status_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("status_id")
            Onstatus_idChanged()
        End Set
    End Property

    Private _status_id As Global.System.Int32
    Private Partial Sub Onstatus_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onstatus_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_classes_m_statuses", "m_statuses")>
    Public Property m_statuses() As m_statuses
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of m_statuses)("QLHSModel.FK_classes_m_statuses", "m_statuses").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of m_statuses)("QLHSModel.FK_classes_m_statuses", "m_statuses").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property m_statusesReference() As EntityReference(Of m_statuses)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of m_statuses)("QLHSModel.FK_classes_m_statuses", "m_statuses")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of m_statuses)("QLHSModel.FK_classes_m_statuses", "m_statuses", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_classes_users", "users")>
    Public Property user() As user
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_classes_users", "users").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_classes_users", "users").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property userReference() As EntityReference(Of user)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_classes_users", "users")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of user)("QLHSModel.FK_classes_users", "users", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_scores_classes", "scores")>
     Public Property scores() As EntityCollection(Of score)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of score)("QLHSModel.FK_scores_classes", "scores")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of score)("QLHSModel.FK_scores_classes", "scores", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_study_dates_classes", "study_dates")>
     Public Property study_dates() As EntityCollection(Of study_dates)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of study_dates)("QLHSModel.FK_study_dates_classes", "study_dates")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of study_dates)("QLHSModel.FK_study_dates_classes", "study_dates", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLHSModel", Name:="m_roles")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class m_roles
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new m_roles object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="role">Initial value of the role property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createm_roles(id As Global.System.Int32, role As Global.System.String, delflg As Global.System.Int32) As m_roles
        Dim m_roles as m_roles = New m_roles
        m_roles.id = id
        m_roles.role = role
        m_roles.delflg = delflg
        Return m_roles
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property role() As Global.System.String
        Get
            Return _role
        End Get
        Set
            OnroleChanging(value)
            ReportPropertyChanging("role")
            _role = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("role")
            OnroleChanged()
        End Set
    End Property

    Private _role As Global.System.String
    Private Partial Sub OnroleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnroleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_users_m_roles", "users")>
     Public Property users() As EntityCollection(Of user)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of user)("QLHSModel.FK_users_m_roles", "users")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of user)("QLHSModel.FK_users_m_roles", "users", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLHSModel", Name:="m_statuses")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class m_statuses
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new m_statuses object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="status">Initial value of the status property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createm_statuses(id As Global.System.Int32, status As Global.System.String, delflg As Global.System.Int32) As m_statuses
        Dim m_statuses as m_statuses = New m_statuses
        m_statuses.id = id
        m_statuses.status = status
        m_statuses.delflg = delflg
        Return m_statuses
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property status() As Global.System.String
        Get
            Return _status
        End Get
        Set
            OnstatusChanging(value)
            ReportPropertyChanging("status")
            _status = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("status")
            OnstatusChanged()
        End Set
    End Property

    Private _status As Global.System.String
    Private Partial Sub OnstatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnstatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_classes_m_statuses", "classes")>
     Public Property classes() As EntityCollection(Of [class])
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of [class])("QLHSModel.FK_classes_m_statuses", "classes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of [class])("QLHSModel.FK_classes_m_statuses", "classes", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLHSModel", Name:="score")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class score
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new score object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="student_id">Initial value of the student_id property.</param>
    ''' <param name="class_id">Initial value of the class_id property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createscore(id As Global.System.Int32, student_id As Global.System.Int32, class_id As Global.System.Int32, delflg As Global.System.Int32) As score
        Dim score as score = New score
        score.id = id
        score.student_id = student_id
        score.class_id = class_id
        score.delflg = delflg
        Return score
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property student_id() As Global.System.Int32
        Get
            Return _student_id
        End Get
        Set
            Onstudent_idChanging(value)
            ReportPropertyChanging("student_id")
            _student_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("student_id")
            Onstudent_idChanged()
        End Set
    End Property

    Private _student_id As Global.System.Int32
    Private Partial Sub Onstudent_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onstudent_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property class_id() As Global.System.Int32
        Get
            Return _class_id
        End Get
        Set
            Onclass_idChanging(value)
            ReportPropertyChanging("class_id")
            _class_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("class_id")
            Onclass_idChanged()
        End Set
    End Property

    Private _class_id As Global.System.Int32
    Private Partial Sub Onclass_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onclass_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property score1() As Nullable(Of Global.System.Double)
        Get
            Return _score1
        End Get
        Set
            Onscore1Changing(value)
            ReportPropertyChanging("score1")
            _score1 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("score1")
            Onscore1Changed()
        End Set
    End Property

    Private _score1 As Nullable(Of Global.System.Double)
    Private Partial Sub Onscore1Changing(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub Onscore1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_scores_classes", "classes")>
    Public Property [class]() As [class]
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLHSModel.FK_scores_classes", "classes").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLHSModel.FK_scores_classes", "classes").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property classReference() As EntityReference(Of [class])
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLHSModel.FK_scores_classes", "classes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of [class])("QLHSModel.FK_scores_classes", "classes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_scores_users", "users")>
    Public Property user() As user
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_scores_users", "users").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_scores_users", "users").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property userReference() As EntityReference(Of user)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLHSModel.FK_scores_users", "users")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of user)("QLHSModel.FK_scores_users", "users", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLHSModel", Name:="study_dates")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class study_dates
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new study_dates object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="class_id">Initial value of the class_id property.</param>
    ''' <param name="study_date">Initial value of the study_date property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createstudy_dates(id As Global.System.Int32, class_id As Global.System.Int32, study_date As Global.System.DateTime, delflg As Global.System.Int32) As study_dates
        Dim study_dates as study_dates = New study_dates
        study_dates.id = id
        study_dates.class_id = class_id
        study_dates.study_date = study_date
        study_dates.delflg = delflg
        Return study_dates
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property class_id() As Global.System.Int32
        Get
            Return _class_id
        End Get
        Set
            Onclass_idChanging(value)
            ReportPropertyChanging("class_id")
            _class_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("class_id")
            Onclass_idChanged()
        End Set
    End Property

    Private _class_id As Global.System.Int32
    Private Partial Sub Onclass_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onclass_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property study_date() As Global.System.DateTime
        Get
            Return _study_date
        End Get
        Set
            Onstudy_dateChanging(value)
            ReportPropertyChanging("study_date")
            _study_date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("study_date")
            Onstudy_dateChanged()
        End Set
    End Property

    Private _study_date As Global.System.DateTime
    Private Partial Sub Onstudy_dateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub Onstudy_dateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_checks_study_dates", "checks")>
     Public Property checks() As EntityCollection(Of check)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of check)("QLHSModel.FK_checks_study_dates", "checks")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of check)("QLHSModel.FK_checks_study_dates", "checks", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_study_dates_classes", "classes")>
    Public Property [class]() As [class]
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLHSModel.FK_study_dates_classes", "classes").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLHSModel.FK_study_dates_classes", "classes").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property classReference() As EntityReference(Of [class])
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLHSModel.FK_study_dates_classes", "classes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of [class])("QLHSModel.FK_study_dates_classes", "classes", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLHSModel", Name:="user")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class user
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new user object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="username">Initial value of the username property.</param>
    ''' <param name="password">Initial value of the password property.</param>
    ''' <param name="role_id">Initial value of the role_id property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createuser(id As Global.System.Int32, username As Global.System.String, password As Global.System.String, role_id As Global.System.Int32, delflg As Global.System.Int32) As user
        Dim user as user = New user
        user.id = id
        user.username = username
        user.password = password
        user.role_id = role_id
        user.delflg = delflg
        Return user
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property username() As Global.System.String
        Get
            Return _username
        End Get
        Set
            OnusernameChanging(value)
            ReportPropertyChanging("username")
            _username = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("username")
            OnusernameChanged()
        End Set
    End Property

    Private _username As Global.System.String
    Private Partial Sub OnusernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnusernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property password() As Global.System.String
        Get
            Return _password
        End Get
        Set
            OnpasswordChanging(value)
            ReportPropertyChanging("password")
            _password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("password")
            OnpasswordChanged()
        End Set
    End Property

    Private _password As Global.System.String
    Private Partial Sub OnpasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fullname() As Global.System.String
        Get
            Return _fullname
        End Get
        Set
            OnfullnameChanging(value)
            ReportPropertyChanging("fullname")
            _fullname = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fullname")
            OnfullnameChanged()
        End Set
    End Property

    Private _fullname As Global.System.String
    Private Partial Sub OnfullnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfullnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property birthday() As Nullable(Of Global.System.DateTime)
        Get
            Return _birthday
        End Get
        Set
            OnbirthdayChanging(value)
            ReportPropertyChanging("birthday")
            _birthday = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("birthday")
            OnbirthdayChanged()
        End Set
    End Property

    Private _birthday As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnbirthdayChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnbirthdayChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property role_id() As Global.System.Int32
        Get
            Return _role_id
        End Get
        Set
            Onrole_idChanging(value)
            ReportPropertyChanging("role_id")
            _role_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("role_id")
            Onrole_idChanged()
        End Set
    End Property

    Private _role_id As Global.System.Int32
    Private Partial Sub Onrole_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onrole_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property school_year_begin() As Nullable(Of Global.System.Int32)
        Get
            Return _school_year_begin
        End Get
        Set
            Onschool_year_beginChanging(value)
            ReportPropertyChanging("school_year_begin")
            _school_year_begin = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("school_year_begin")
            Onschool_year_beginChanged()
        End Set
    End Property

    Private _school_year_begin As Nullable(Of Global.System.Int32)
    Private Partial Sub Onschool_year_beginChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onschool_year_beginChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property school_year_end() As Nullable(Of Global.System.Int32)
        Get
            Return _school_year_end
        End Get
        Set
            Onschool_year_endChanging(value)
            ReportPropertyChanging("school_year_end")
            _school_year_end = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("school_year_end")
            Onschool_year_endChanged()
        End Set
    End Property

    Private _school_year_end As Nullable(Of Global.System.Int32)
    Private Partial Sub Onschool_year_endChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onschool_year_endChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_checks_users", "checks")>
     Public Property checks() As EntityCollection(Of check)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of check)("QLHSModel.FK_checks_users", "checks")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of check)("QLHSModel.FK_checks_users", "checks", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_classes_users", "classes")>
     Public Property classes() As EntityCollection(Of [class])
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of [class])("QLHSModel.FK_classes_users", "classes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of [class])("QLHSModel.FK_classes_users", "classes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_users_m_roles", "m_roles")>
    Public Property m_roles() As m_roles
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of m_roles)("QLHSModel.FK_users_m_roles", "m_roles").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of m_roles)("QLHSModel.FK_users_m_roles", "m_roles").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property m_rolesReference() As EntityReference(Of m_roles)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of m_roles)("QLHSModel.FK_users_m_roles", "m_roles")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of m_roles)("QLHSModel.FK_users_m_roles", "m_roles", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLHSModel", "FK_scores_users", "scores")>
     Public Property scores() As EntityCollection(Of score)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of score)("QLHSModel.FK_scores_users", "scores")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of score)("QLHSModel.FK_scores_users", "scores", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


